### ISSUE TITLE
Unexpectedly found nil

### ISSUE THREAD

**Issue by hmdalmulim** [BadhanGanesh/BJOTPViewController#13] opened 2022-04-24 01:15 UTC
after received OTP i got 
BJOTPViewController/BJOTPViewController.swift:305: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

 @objc public var authenticateButtonTitle: String = "AUTHENTICATE" {
        willSet {
            self.authenticateButton.setTitle(newValue, for: .normal)
        }
    }
and App was stopped

**Comment by BadhanGanesh-HappyFox** [comment] 2022-05-02 16:20
@hmdalmulim Thanks for reporting. This will be fixed in the next release - v2.6.0.

**Edit:** The issue is fixed in the above-mentioned release. LIVE now.

**Closed as completed** 2022-08-17 19:57 UTC
Labels: fixed
